name: UI Build and Deploy

on:
  push:
    branches:
      - main # Production build
      - staging # Staging build
  workflow_dispatch:

jobs:
  build-deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      run-tests: true
      run-build: true
      run-docker: true
      environment-tag: ${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
    secrets:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
