name: UI CI

on:
  push:
    branches-ignore: [main] # Run on all branches except main
  pull_request:
    branches: [main] # Run on PRs targeting main

jobs:
  ci-process:
    uses: ./.github/workflows/reusable.yml
    with:
      run-tests: true
      run-build: true
      run-docker: false
    secrets:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
