name: Frontend CI

on:
  push:
    branches-ignore: [main] # Run on all branches except main
  pull_request:
    branches: [main] # Run on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint || true # Allow linting to fail without stopping workflow

      - name: Run type check
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
