name: Create Main PR from Staging

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  create-pr-to-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Create PR from Staging to Main if needed
        run: |
          # Check if there are differences between staging and main
          if git diff --quiet origin/staging origin/main; then
            echo "No differences between staging and main, skipping PR creation"
            exit 0
          fi

          # Create PR using GitHub CLI
          gh pr create --base main --head staging \
            --title "Sync: Promote Staging to Main" \
            --body "This is an automated PR to promote changes from staging to main after testing." \
            || echo "PR already exists or could not be created"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
